TIME = 'TIME'
MARKET = 'MARKET'
VOLUME = 'VOLUME'

BASE_VOLUME = 'BASE_VOLUME'
QUOTE_VOLUME = 'QUOTE_VOLUME'
ASK = 'ASK'
BID = 'BID'

OPEN = 'OPEN'
CLOSE = 'CLOSE'
HIGH = 'HIGH'
LOW = 'LOW'

STRATEGY = 'STRATEGY'
TRADING_SIGNAL = 'TRADING_SIGNAL'

POLONIEX = 'POLONIEX'
BITTREX = 'BITTREX'
EXCHANGES = [POLONIEX, BITTREX]

MAKER = 'maker'
TAKER = 'taker'

FEES = {BITTREX: {MAKER: 0.25,
                  TAKER: 0.25},
        POLONIEX: {MARKET: 0.15,
                   TAKER: 0.25}}
